# -*- coding: utf-8 -*-
"""ColourDetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a-skki0w8G_1C-s8euu1JatMhXsi2NsW

# **Colour Recognition Tool**

This notebook identifies the colour under a double clicked pixel in an uploaded image.

### Importing Libraries
"""

import glob
import os

import cv2
import kagglehub
import pandas as pd

"""### Importing the dataset"""

os.environ["KAGGLEHUB_CACHE"] = "/content/my_datasets"

downloaded_path = kagglehub.dataset_download("adikurniawan/color-dataset-for-color-recognition")
print("Path to dataset files:", downloaded_path)

"""### Locating the class folders"""

KNOWN_CLASSES = {"black", "blue", "brown", "green", "grey", "gray",
                  "orange", "red", "violet", "white", "yellow"}


def find_class_root(base_path, known_classes=KNOWN_CLASSES, min_matches=5):
    """Search base_path for the directory that holds the colour-class subfolders."""
    for root, dirs, _files in os.walk(base_path):
        dir_names = {d.lower() for d in dirs}
        if len(dir_names & known_classes) >= min_matches:
            return root
    return base_path


dataset_path = find_class_root(downloaded_path)
print("Using class-folder root:", dataset_path)
print("Classes found:", sorted(os.listdir(dataset_path)))

"""### Building Colour Profiles from the Image Dataset

For each class folder, average the mean colour of every sample image to get one representative
(R, G, B) value per class.
"""

def build_colour_profiles(class_root):
    """Compute an average R/G/B profile for each colour class folder."""
    profiles = []
    image_exts = (".jpg", ".jpeg", ".png", ".bmp")

    class_dirs = sorted(
        d for d in os.listdir(class_root) if os.path.isdir(os.path.join(class_root, d))
    )

    for class_name in class_dirs:
        class_dir = os.path.join(class_root, class_name)
        image_files = [f for f in os.listdir(class_dir) if f.lower().endswith(image_exts)]

        r_sum = g_sum = b_sum = 0.0
        counted = 0

        for filename in image_files:
            img = cv2.imread(os.path.join(class_dir, filename))
            if img is None:
                continue

            b_mean, g_mean, r_mean = cv2.mean(img)[:3]
            r_sum += r_mean
            g_sum += g_mean
            b_sum += b_mean
            counted += 1

        if counted == 0:
            print(f"Warning: no readable images found for class '{class_name}', skipping.")
            continue

        profiles.append(
            {
                "color_name": class_name,
                "R": r_sum / counted,
                "G": g_sum / counted,
                "B": b_sum / counted,
            }
        )

    return pd.DataFrame(profiles)


colour_data = build_colour_profiles(dataset_path)
colour_data

"""### Closest Colour Match"""

def get_colour_name(red, green, blue, colour_data):
    """Return the closest colour class name based on RGB distance."""
    minimum_distance = float("inf")
    closest_colour = "Unknown"

    for i in range(len(colour_data)):
        distance = (
            abs(red - int(colour_data.loc[i, "R"]))
            + abs(green - int(colour_data.loc[i, "G"]))
            + abs(blue - int(colour_data.loc[i, "B"]))
        )

        if distance <= minimum_distance:
            minimum_distance = distance
            closest_colour = colour_data.loc[i, "color_name"]

    return closest_colour

"""### Colour Picker"""

class ColourPicker:
    """Tracks the last double-clicked pixel and draws an info bar for it."""

    def __init__(self, colour_data):
        self.colour_data = colour_data
        self.clicked = False
        self.r = self.g = self.b = 0
        self.xpos = self.ypos = 0

    def draw_function(self, event, x, y, flags, param):
        """Mouse callback: param is a dict holding the current image under 'image'."""
        if event == cv2.EVENT_LBUTTONDBLCLK:
            image = param["image"]
            if image is None:
                return

            self.clicked = True
            self.xpos, self.ypos = x, y
            b, g, r = image[y, x]
            self.b, self.g, self.r = int(b), int(g), int(r)

    def annotate(self, display_image):
        """Draw the colour swatch + label onto a copy of the image, if a click has happened."""
        if self.clicked:
            colour_name = get_colour_name(self.r, self.g, self.b, self.colour_data)
            text = f"{colour_name} R={self.r} G={self.g} B={self.b}"

            cv2.rectangle(display_image, (20, 20), (850, 60), (self.b, self.g, self.r), -1)

            text_colour = (255, 255, 255)
            if self.r + self.g + self.b >= 600:
                text_colour = (0, 0, 0)

            cv2.putText(
                display_image,
                text,
                (50, 50),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.8,
                text_colour,
                2,
                cv2.LINE_AA,
            )

        return display_image

"""### Image Detection"""

from google.colab.patches import cv2_imshow

def run_image_mode(colour_data, image_path):
    """Colab-friendly colour detection: enter pixel coordinates instead of clicking (no GUI window support in Colab)."""
    if not os.path.exists(image_path):
        raise FileNotFoundError(f"Image file not found: {image_path}")

    image = cv2.imread(image_path)
    if image is None:
        raise ValueError("Could not read image. Check the file format or path.")

    picker = ColourPicker(colour_data)
    height, width = image.shape[:2]

    print(f"Image size: {width} x {height} (width x height)")
    print("Enter pixel coordinates to sample a colour, or type 'q' to quit.\n")

    cv2_imshow(image)

    while True:
        user_input = input("Enter 'x,y' coordinates (or 'q' to quit): ").strip()

        if user_input.lower() == "q":
            break

        try:
            x_str, y_str = user_input.split(",")
            x, y = int(x_str.strip()), int(y_str.strip())
        except ValueError:
            print("Please enter coordinates in the form: x,y (e.g. 120,340)")
            continue

        if not (0 <= x < width and 0 <= y < height):
            print(f"Coordinates out of bounds. Must be within 0-{width - 1}, 0-{height - 1}.")
            continue

        # Reuse the existing mouse-callback logic by simulating a double-click at (x, y)
        picker.draw_function(cv2.EVENT_LBUTTONDBLCLK, x, y, None, {"image": image})
        display_image = picker.annotate(image.copy())

        colour_name = get_colour_name(picker.r, picker.g, picker.b, colour_data)
        print(f"Colour at ({x}, {y}): {colour_name} (R={picker.r}, G={picker.g}, B={picker.b})")

        cv2_imshow(display_image)

"""## **Uploading An Image**"""

from google.colab import files

uploaded = files.upload()  # opens a file picker — choose an image from your device

if not uploaded:
    raise ValueError("No file was uploaded.")

IMAGE_PATH = next(iter(uploaded))  # filename of the uploaded image
print(f"Uploaded image saved as: {IMAGE_PATH}")

run_image_mode(colour_data, image_path=IMAGE_PATH)